# docker-compose.yml
# Add this top-level entry
version: '3.3'
services:
  redis:
    image: redislabs/rejson:latest
    container_name: redis
    expose:
      - 6379
    ports:
      - "6379:6379"
  kondo-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    expose:
      - 8000
  kondo-repo-server:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: "python run_repo_server.py"