# ---------------------------------------------
# Rooms for Room Engine
# ---------------------------------------------
[rooms]
terraform = 'https://github.com/kondo-io/terraform-room.git'
java = 'https://github.com/kondo-io/room-java.git'
flask = 'https://github.com/kondo-io/room-flask.git'
