from kondo_backend import repo_processor
import pytest
import responses
from flask import app


@responses.activate
def test_get_installations():
    responses.add(
        responses.GET,
        "https://api.github.com/app/installations",
        json=[
            {
                "id": 932356,
                "account": {
                    "login": "devopslibrary",
                    "id": 11233903,
                    "node_id": "MDEyOk9yZ2FuaXphdGlvbjExMjMzOTAz",
                    "avatar_url": "https://avatars3.githubusercontent.com/u/11233903?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/devopslibrary",
                    "html_url": "https://github.com/devopslibrary",
                    "followers_url": "https://api.github.com/users/devopslibrary/followers",
                    "following_url": "https://api.github.com/users/devopslibrary/following{/other_user}",
                    "gists_url": "https://api.github.com/users/devopslibrary/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/devopslibrary/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/devopslibrary/subscriptions",
                    "organizations_url": "https://api.github.com/users/devopslibrary/orgs",
                    "repos_url": "https://api.github.com/users/devopslibrary/repos",
                    "events_url": "https://api.github.com/users/devopslibrary/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/devopslibrary/received_events",
                    "type": "Organization",
                    "site_admin": False,
                },
                "repository_selection": "all",
                "access_tokens_url": "https://api.github.com/app/installations/932356/access_tokens",
                "repositories_url": "https://api.github.com/installation/repositories",
                "html_url": "https://github.com/organizations/devopslibrary/settings/installations/932356",
                "app_id": 30108,
                "target_id": 11233903,
                "target_type": "Organization",
                "permissions": {
                    "administration": "write",
                    "checks": "write",
                    "contents": "write",
                    "pull_requests": "write",
                    "repository_hooks": "write",
                    "statuses": "write",
                    "members": "read",
                    "organization_hooks": "read",
                    "metadata": "read",
                    "vulnerability_alerts": "read",
                },
                "events": [
                    "check_run",
                    "check_suite",
                    "commit_comment",
                    "create",
                    "delete",
                    "public",
                    "pull_request",
                    "pull_request_review",
                    "pull_request_review_comment",
                    "push",
                    "release",
                    "repository",
                    "repository_dispatch",
                    "status",
                ],
                "created_at": "2019-05-07T01:27:52.000Z",
                "updated_at": "2019-05-07T01:27:52.000Z",
                "single_file_name": None,
            },
            {
                "id": 898100,
                "account": {
                    "login": "kondo-io",
                    "id": 49795176,
                    "node_id": "MDEyOk9yZ2FuaXphdGlvbjQ5Nzk1MTc2",
                    "avatar_url": "https://avatars0.githubusercontent.com/u/49795176?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/kondo-io",
                    "html_url": "https://github.com/kondo-io",
                    "followers_url": "https://api.github.com/users/kondo-io/followers",
                    "following_url": "https://api.github.com/users/kondo-io/following{/other_user}",
                    "gists_url": "https://api.github.com/users/kondo-io/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/kondo-io/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/kondo-io/subscriptions",
                    "organizations_url": "https://api.github.com/users/kondo-io/orgs",
                    "repos_url": "https://api.github.com/users/kondo-io/repos",
                    "events_url": "https://api.github.com/users/kondo-io/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/kondo-io/received_events",
                    "type": "Organization",
                    "site_admin": False,
                },
                "repository_selection": "all",
                "access_tokens_url": "https://api.github.com/app/installations/898100/access_tokens",
                "repositories_url": "https://api.github.com/installation/repositories",
                "html_url": "https://github.com/organizations/kondo-io/settings/installations/898100",
                "app_id": 30108,
                "target_id": 49795176,
                "target_type": "Organization",
                "permissions": {
                    "administration": "write",
                    "checks": "write",
                    "contents": "write",
                    "pull_requests": "write",
                    "repository_hooks": "write",
                    "statuses": "write",
                    "members": "read",
                    "organization_hooks": "read",
                    "metadata": "read",
                    "vulnerability_alerts": "read",
                },
                "events": [
                    "check_run",
                    "check_suite",
                    "commit_comment",
                    "create",
                    "delete",
                    "public",
                    "pull_request",
                    "pull_request_review",
                    "pull_request_review_comment",
                    "push",
                    "release",
                    "repository",
                    "repository_dispatch",
                    "status",
                ],
                "created_at": "2019-05-06T00:30:41.000Z",
                "updated_at": "2019-05-06T00:30:41.000Z",
                "single_file_name": None,
            },
        ],
        status=200,
        match_querystring=True,
    )
    installations = repo_processor.get_installations.get_installations()
    assert installations == [
        {"id": 932356, "org": "devopslibrary"},
        {"id": 898100, "org": "kondo-io"},
    ]
